app:
  build: ../../
  dockerfile: docker/release/Dockerfile
  volumes_from: 
    - webroot
  links:
    - db    
  environment: 
    DJANGO_SETTINGS_MODULE : todobackend.settings.release
    D_USER: postgres
    D_PASSWORD: '123'
    D_NAME: todobackend
    D_HOST: db
  command:
    - uwsgi
    - "--socket /var/www/todobackend/todobackend.sock"
    - "--chmod-socket=666"
    - "--module todobackend.wsgi"
    - "--master"
    - "--die-on-term"

test:
  image: ysinjab/todobackend-spec
  links:
    - nginx
  environment:
    URL: http://nginx:8000/todos
    JUNIT_REPORT_PATH: /reports/acceptance.xml
    JUNIT_REPORT_STACK: 1
  command: --reporter mocha-jenkins-reporter

webroot:
  build: ../../
  dockerfile: docker/release/Dockerfile
  volumes:
    - /var/www/todobackend
  entrypoint: "true"

nginx:
  image: nginx
  volumes:
    - ./todobackend.conf:/etc/nginx/conf.d/todobackend.conf
  links:
    - app
  ports:
    - "8000:8000"
  volumes_from:
    - webroot
db:
  image: postgres
  hostname: db
  expose:
    - "5432"
  environment:
    POSTGRES_PASSWORD: 123
    POSTGRES_DB: todobackend
    
